services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - back
      - front
    restart: unless-stopped

  back:
    build:
      context: ./back
    container_name: back
    expose:
      - "4000"
    volumes:
      - ./back:/app         # bind mount des backend-codes
      - /app/node_modules  # node_modules im container, damit es nicht vom Host überschrieben wird (bei nodejs)
    working_dir: /app
    restart: unless-stopped

  front:
    build:
      context: ./front
    container_name: front
    expose:
      - "4001"
    volumes:
      - ./front:/app         # bind mount des frontend-codes
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped
