services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front/public:/usr/share/nginx/html:ro
    depends_on:
      - back
      - front
    restart: unless-stopped

  back:
    build:
      context: ./back
    container_name: back
    expose:
      - "4000"
    volumes:
      - ./back:/app
      - /app/node_modules
      - ./db:/app/database
    working_dir: /app
    restart: unless-stopped

  front:
    build:
      context: ./front
    container_name: front
    expose:
      - "4001"
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped
