FROM nginx:stable-alpine

RUN apk add --no-cache openssl bash

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/certs

COPY generate-certs.sh /usr/local/bin/generate-certs.sh
RUN chmod +x /usr/local/bin/generate-certs.sh

CMD ["/bin/bash", "-c", "/usr/local/bin/generate-certs.sh && nginx -g 'daemon off;'"]
